name: Build Go-React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # استفاده از سرورهای خود گیت‌هاب

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🛠️ Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: 🚚 Copy dist to Go backend
        run: |
          rm -rf backend/cmd/api/dist
          cp -r frontend/dist backend/cmd/api/

      - name: 🐹 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: 🏗️ Build Go Backend
        working-directory: ./backend
        run: GOOS=linux GOARCH=amd64 go build -o dta770 ./cmd/api

      - name: 📦 Upload Artifact (Ready to download)
        uses: actions/upload-artifact@v4
        with:
          name: dta770-linux-amd64 # اسمی که موقع دانلود می‌بینی
          path: backend/dta770     # مسیر فایلی که باید آپلود بشه