name: Deploy Go-React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # تغییر به رانر سرور خودت

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🛠️ Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: 🚚 Copy dist to Go backend
        run: |
          rm -rf backend/cmd/api/dist
          cp -r frontend/dist backend/cmd/api/

      - name: 🐹 Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: 🏗️ Build Go Backend
        working-directory: ./backend
        run: GOOS=linux GOARCH=amd64 go build -o dta770 ./cmd/api

      - name: 🚀 Deploy and Restart Service
        # این مرحله جایگزین ssh و scp شد
        run: |
          sudo cp backend/dta770 /opt/dta770/dta770
          sudo chmod +x /opt/dta770/dta770
          sudo systemctl restart dta770